### ISSUE TITLE
Help Setup

### ISSUE THREAD

**Issue by DevJoey** [BenCodez/VotifierPlus#10]
Hey, can you help me setting up VotifierPlus on Bungeecord?

My BungeeConfig:
```
Debug: true
host: 0.0.0.0
port: 8192
Forwarding:
  citybuild:
    Enabled: true
    Host: '127.0.0.1'
    Port: '46179'
    Key: 'here i have the public key from my citybuilds rsa'

```

My SpigotConfig:
```
# Debug levels:
# NONE
# INFO
# EXTRA
DebugLevel: NONE
host: 0.0.0.0
port: 46179
Forwarding:
  server1:
    Enabled: false
    Host: ''
    Port: ''
    Key: ''
```

Now if i get a vote, in the bungee console this happens
```
[16:54:01 INFO] [VotifierPlus]: Debug: Received vote record -> Vote (from:minecraft-server.eu username:JoeyPlayzTV address:212.86.48.0 timeStamp:1622732016)
[16:54:01 INFO] [VotifierPlus]: Debug: Sending vote to citybuild
[16:54:01 INFO] [VotifierPlus]: Failed to send vote to citybuild(127.0.0.1:0): Vote (from:minecraft-server.eu username:JoeyPlayzTV address:212.86.48.0 timeStamp:1622732016), ignore this if server is offline
[16:54:01 ERROR]: java.net.ConnectException: Connection refused (Connection refused)
[16:54:01 ERROR]:       at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[16:54:01 ERROR]:       at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[16:54:01 ERROR]:       at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[16:54:01 ERROR]:       at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[16:54:01 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[16:54:01 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:609)
[16:54:01 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:198)
```

Why it says (127.0.0.1:0) in debug. i have set the port to 46179 and not to 0 can it be a issue of your code?

**Comment by BenCodez** [comment]
Send the startup log of the spigot server
