### ISSUE TITLE
Failed to send vote

### ISSUE THREAD

**Issue by tankinnwow** [BenCodez/VotifierPlus#13]
Not sure if this is a me issue but maybe someone can assist me.
I am using both Waterfall and Paper 1.17 servers running java 16.

I setup VoteifierPlus on the Proxy and Hub servers.

Proxy Config:
Debug: true
host: 0.0.0.0
port: 8192
Forwarding:
  Hub:
    Enabled: true
    Host: '172.18.0.1'
    Port: '8193'
    Key: 'used the hubs public key'

Hub Config:
DebugLevel: INFO
host: 0.0.0.0
port: 8193
Forwarding:
  server1:
    Enabled: false
    Host: ''
    Port: ''
    Key: ''

When i use a vote tester like https://mctools.org/votifier-tester i get this error on the proxy:

[21:26:31 INFO] [VotifierPlus]: Failed to send vote to Hub(172.18.0.1:0): Vote (from:MCTools.org username:RainbowDash__ address:REMOVED timeStamp:1625261189), ignore this if server is offline
[21:26:31 ERROR]: java.net.SocketTimeoutException: Connect timed out
[21:26:31 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:26:31 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[21:26:31 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[21:26:31 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:645)
[21:26:31 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:198)

Thanks in advance for any help :)

**Comment by BenCodez** [comment]
Is the hub able to bind to the port on 8193? Seems like something is preventing the connection (assuming everything else is correct)

**Comment by tankinnwow** [comment]
The hub is able to bind to 8193. I had NuVotifier setup using the same port configuration.

**Comment by BenCodez** [comment]
Then I got no idea. Stick with nuvotifier if that works?

**Comment by tankinnwow** [comment]
i might have to. :( i kept running into an issue on server shutdown where NuVotifier was not shutting down properly so i was hoping to find a new plugin that was being updated.

Thanks for the response.

**Comment by BenCodez** [comment]
It should work the same as nuvotifier in theory

**Comment by tankinnwow** [comment]
I am going to run a few more network tests just to make sure i configured my network properly. I have my entire system locked down so sometimes i have to put in extra work to make things work. I went a bit overboard when setting my servers up so it might just be a me problem.

**Comment by tankinnwow** [comment]
Not sure if this helps but i am getting this one Hub

[23:55:57 WARN]: [VotifierPlus] Protocol error. Ignoring packet - Socket closed
[23:55:57 WARN]: java.net.SocketException: Socket closed
[23:55:57 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:689)
[23:55:57 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:762)
[23:55:57 WARN]:        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:681)
[23:55:57 WARN]:        at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:647)
[23:55:57 WARN]:        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:623)
[23:55:57 WARN]:        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:580)
[23:55:57 WARN]:        at java.base/java.net.ServerSocket.accept(ServerSocket.java:538)
[23:55:57 WARN]:        at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:131)

**Comment by BenCodez** [comment]
So something causes that to close, not sure what though

**Comment by tankinnwow** [comment]
Might it have something to do with 1.17?

**Comment by BenCodez** [comment]
Are you on the latest version of VotifierPlus? If so then it shouldn't matter

**Comment by tankinnwow** [comment]
VotifierPlus 1.0.4

**Comment by BenCodez** [comment]
I got no idea right now
