### ISSUE TITLE
Config read error

### ISSUE THREAD

**Issue by nomadjimbob** [BenCodez/VotifierPlus#17]
I am receiving the following startup error:

```
13.02 07:10:33 [Server] INFO Enabling VotifierPlus v1.0.5
13.02 07:10:33 [Server] WARN Loaded class com.comphenix.protocol.events.PacketListener from ProtocolLib v4.8.0-SNAPSHOT-b540 which is not a depend, softdepend or loadbefore of this plugin.
13.02 07:10:33 [Server] ERROR Error occurred while enabling VotifierPlus v1.0.5 (Is it up to date?)
13.02 07:10:33 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.isConfigurationSection(String)" because the return value of "com.bencodez.VotifierPlus.advancedcore.data.ServerData.getData()" is null
13.02 07:10:33 [Server] INFO at com.bencodez.VotifierPlus.advancedcore.api.permissions.PermissionHandler.<init>(PermissionHandler.java:36) ~[VotifierPlus.jar:?]
13.02 07:10:33 [Server] INFO at com.bencodez.VotifierPlus.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:468) ~[VotifierPlus.jar:?]
13.02 07:10:33 [Server] INFO at com.bencodez.VotifierPlus.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:853) ~[VotifierPlus.jar:?]
13.02 07:10:33 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
13.02 07:10:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
13.02 07:10:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
13.02 07:10:33 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1533]
13.02 07:10:33 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
13.02 07:10:33 [Server] INFO Disabling VotifierPlus v1.0.5
13.02 07:10:33 [Server] INFO Votifier disabled.
```

**Config**
```
host: 139.99.214.50
port: 36363
Forwarding:
  server1:
    Enabled: true
    Host: 139.99.214.50
    Port: 36363
    Key: 'the-key'
```

Purpur version: git-Purpur-1533 (MC: 1.18.1)
Java 17

Occurs even with a clean install and clean config.

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotifierPlus/ better?

**Comment by nomadjimbob** [comment]
Yes, thanks
