### ISSUE TITLE
[VotifierPlus] Plugin VotifierPlus v1.0.6 generated an exception while executing task 2369

### ISSUE THREAD

**Issue by LifeSand** [BenCodez/VotifierPlus#19]
[06:42:33 WARN]: [VotifierPlus] Plugin VotifierPlus v1.0.6 generated an exception while executing task 2369
java.lang.NullPointerException: Cannot invoke "com.bencodez.VotifierPlus.advancedcore.api.user.userstorage.sql.Database.getTables()" because "this.database" is null
        at com.bencodez.VotifierPlus.advancedcore.AdvancedCorePlugin.getSQLiteUserTable(AdvancedCorePlugin.java:355) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.UserData.getSQLiteRow(UserData.java:232) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.UserData.getKeys(UserData.java:193) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.UserData.getKeys(UserData.java:178) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.usercache.UserDataCache.cache(UserDataCache.java:47) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.usercache.UserDataManager.cacheUser(UserDataManager.java:71) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.AdvancedCoreUser.cache(AdvancedCoreUser.java:206) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.UserData.getString(UserData.java:274) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.UserData.getString(UserData.java:241) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.user.AdvancedCoreUser.isCheckWorld(AdvancedCoreUser.java:644) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.listeners.WorldChangeEvent$1.run(WorldChangeEvent.java:47) ~[VotifierPlus.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-204]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-204]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-204]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by thedarkcr0w** [comment]
have the same issue

**Comment by BenCodez** [comment]
Does this work? https://bencodez.com/job/VotifierPlus/

**Comment by LifeSand** [comment]
Yes, working fine... the ip address of my hosting has changed and generated the error, Sorry for reporting this issue.
