### ISSUE TITLE
I need help setting up VotifierPlus

### ISSUE THREAD

**Issue by FlameBeast25** [BenCodez/VotifierPlus#29]
I tried finding yt tutorials on how to set up, however, they were all for hosted servers. I am running a local server on my own PC. How do I set it up?

**Comment by BenCodez** [comment]
Port forwarding and follow the tutorials, same process

**Comment by FlameBeast25** [comment]
> Port forwarding and follow the tutorials, same process

1) thanks for the quick reply
2) I don't see a port folder on my server

![image](https://user-images.githubusercontent.com/89554319/189778396-dd61828d-a06e-4a9c-8146-15922610324f.png)

**Comment by BenCodez** [comment]
Search up port forwarding, it's not a plugin or folder.

**Comment by FlameBeast25** [comment]
> Search up port forwarding, it's not a plugin or folder.

I have done port forwarding to set up my server in the first place, but idk what exactly to do for votifier.

**Comment by BenCodez** [comment]
Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it

**Comment by FlameBeast25** [comment]
> Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it

The forwarded port is the default port, one yt tutorial said not to use that one

**Comment by FlameBeast25** [comment]
> Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it

Also stop talking to me like I have 500 IQ, I am not a dev on these type of projects can you please explain clearly?

**Comment by BenCodez** [comment]
> > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> 
> The forwarded port is the default port, one yt tutorial said not to use that one

That's for shared hosts, should be fine for personal hosting

> > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> 
> Also stop talking to me like I have 500 IQ, I am not a dev on these type of projects can you please explain clearly?

Should be able to research if you plan to host this yourself, votifier is a real pain even for experienced people to the point I created this wiki page: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by FlameBeast25** [comment]
> > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > 
> > 
> > The forwarded port is the default port, one yt tutorial said not to use that one
> 
> That's for shared hosts, should be fine for personal hosting
> 
> > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > 
> > 
> > Also stop talking to me like I have 500 IQ, I am not a dev on these type of projects can you please explain clearly?
> 
> Should be able to research if you plan to host this yourself, votifier is a real pain even for experienced people to the point I created this wiki page: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

Why do all you devs have trash support.

**Comment by BenCodez** [comment]
> > > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > > 
> > > 
> > > The forwarded port is the default port, one yt tutorial said not to use that one
> > 
> > 
> > That's for shared hosts, should be fine for personal hosting
> > > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > > 
> > > 
> > > Also stop talking to me like I have 500 IQ, I am not a dev on these type of projects can you please explain clearly?
> > 
> > 
> > Should be able to research if you plan to host this yourself, votifier is a real pain even for experienced people to the point I created this wiki page: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
> 
> Why do all you devs have trash support.

Because I am not paid for this.

**Comment by FlameBeast25** [comment]
> > > > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > > > 
> > > > 
> > > > The forwarded port is the default port, one yt tutorial said not to use that one
> > > 
> > > 
> > > That's for shared hosts, should be fine for personal hosting
> > > > > Use the forwarded port, configure votifier with host/port, use votifier key on website, should be it
> > > > 
> > > > 
> > > > Also stop talking to me like I have 500 IQ, I am not a dev on these type of projects can you please explain clearly?
> > > 
> > > 
> > > Should be able to research if you plan to host this yourself, votifier is a real pain even for experienced people to the point I created this wiki page: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
> > 
> > 
> > Why do all you devs have trash support.
> 
> Because I am not paid for this.

Makes Sense, I recommend making a premium version or smth
Anyway, I watched apex hosting video but hallway through the tutorial the guy said: "you know what to do at this point" and left me hanging.
What do I fill out here (left vonfig is votingplugin, right config is votifierplus):
![image](https://user-images.githubusercontent.com/89554319/189780327-ffce7c36-30a7-4a3a-85ad-33d5826a2bf1.png)

**Comment by BenCodez** [comment]
Change the port if votifierplus to what you port forward, set your ip/port in the voting website with the public key in votifierplus. See if it works.

Would do that before votingplugin configuration and make sure you get that working with confirmation in console

**Comment by FlameBeast25** [comment]
> Change the port if votifierplus to what you port forward, set your ip/port in the voting website with the public key in votifierplus. See if it works.
> 
> Would do that before votingplugin configuration and make sure you get that working with confirmation in console

1) Am I supposed to use default port since that's the one i used to set up server
2) which lines? There are multiple places where you can enter in port on both configs

**Comment by FlameBeast25** [comment]
> Change the port if votifierplus to what you port forward, set your ip/port in the voting website with the public key in votifierplus. See if it works.
> 
> Would do that before votingplugin configuration and make sure you get that working with confirmation in console

3) How to get key

**Comment by BenCodez** [comment]
1. Doesn't really matter what port, just one that is open and port forwarded
2. First port line top of file
3. votifierplus folder under keys, public key only, copy all text

**Comment by FlameBeast25** [comment]
> 1. Doesn't really matter what port, just one that is open and port forwarded
> 2. First port line top of file
> 3. votifierplus folder under keys, public key only, copy all text

for 3) what key u talking about

![image](https://user-images.githubusercontent.com/89554319/189781191-0bace9c5-d403-4f99-a76f-0e76761752ba.png)

**Comment by BenCodez** [comment]
that's votingplugin, look in votifierplus

**Comment by FlameBeast25** [comment]
> that's votingplugin, look in votifierplus

![image](https://user-images.githubusercontent.com/89554319/189781730-0c4b9eb0-4ea9-44c5-a6b4-2be90c0e0dac.png)

**Comment by FlameBeast25** [comment]
> > that's votingplugin, look in votifierplus
> 
> ![image](https://user-images.githubusercontent.com/89554319/189781730-0c4b9eb0-4ea9-44c5-a6b4-2be90c0e0dac.png)

this was when i did the test

**Comment by BenCodez** [comment]
send the full log file. Probably didn't bind to the ip/port. Might need a different port

**Comment by FlameBeast25** [comment]
> send the full log file. Probably didn't bind to the ip/port. Might need a different port

it worked
![image](https://user-images.githubusercontent.com/89554319/189781981-9bb1f52b-1f3b-442f-b16a-4a0fa6fcaaf8.png)
but how to fix error how to send log file

**Comment by FlameBeast25** [comment]
> send the full log file. Probably didn't bind to the ip/port. Might need a different port

[20:20:48 INFO]: [DiscordSRV] FlameBeast25 was sent a notice for having a degraded user experience due to LunarClient (You can use EnableIncompatibleClientAlert to disable the message if you'd like (Not recommended))
[20:21:06 INFO]: [BuycraftX] Sending 1 analytic events
[20:21:15 INFO]: [BuycraftX] Fetching all due players...
[20:21:15 INFO]: [BuycraftX] Fetched due players (0 found).
[20:23:15 INFO]: [BuycraftX] Fetching all due players...
[20:23:15 INFO]: [BuycraftX] Fetched due players (0 found).
[20:25:15 INFO]: [BuycraftX] Fetching all due players...
[20:25:15 INFO]: [BuycraftX] Fetched due players (0 found).
[20:27:15 INFO]: [BuycraftX] Fetching all due players...
[20:27:16 INFO]: [BuycraftX] Fetched due players (0 found).
[20:27:40 INFO]: FlameBeast25 issued server command: /pluginmanager reload
[20:27:51 INFO]: FlameBeast25 issued server command: /votifierplus Reload
[20:27:52 WARN]: [VotifierPlus] Protocol error. Ignoring packet - Socket closed
[20:27:52 ERROR]: [VotifierPlus] Error initializing vote receiver. Please verify that the configured
[20:27:52 ERROR]: [VotifierPlus] IP address and port are not already in use. This is a common problem
[20:27:52 ERROR]: [VotifierPlus] with hosting services and, if so, you should check with your hosting provider.
[20:27:52 WARN]: java.net.BindException: Address already in use: bind
[20:27:52 WARN]:        at java.base/sun.nio.ch.Net.bind0(Native Method)
[20:27:52 WARN]:        at java.base/sun.nio.ch.Net.bind(Net.java:555)
[20:27:52 WARN]:        at java.base/sun.nio.ch.Net.bind(Net.java:544)
[20:27:52 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
[20:27:52 WARN]:        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
[20:27:52 WARN]:        at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.net.VoteReceiver.initialize(VoteReceiver.java:87)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.net.VoteReceiver.<init>(VoteReceiver.java:81)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.VotifierPlus$2.<init>(VotifierPlus.java:116)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.VotifierPlus.loadVoteReceiver(VotifierPlus.java:116)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.VotifierPlus.reload(VotifierPlus.java:295)
[20:27:52 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.commands.CommandLoader$2.execute(CommandLoader.java:69)
[20:27:52 WARN]:        at VotifierPlus.jar//com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446)
[20:27:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:27:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:27:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:27:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:27:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:27:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:27:52 ERROR]: [VotifierPlus] Votifier did not initialize properly!
[20:27:58 INFO]: FlameBeast25 issued server command: /votifierplus Help
[20:28:04 INFO]: FlameBeast25 issued server command: /votifierplus test FlameBeast25 test
[20:29:16 INFO]: [BuycraftX] Fetching all due players...
[20:29:16 INFO]: [BuycraftX] Fetched due players (0 found).
[20:31:06 INFO]: FlameBeast25 issued server command: /votifierplus test FlameBeast25 hello
[20:31:16 INFO]: [BuycraftX] Fetching all due players...
[20:31:16 INFO]: [BuycraftX] Fetched due players (0 found).

**Comment by BenCodez** [comment]
[20:27:52 ERROR]: [VotifierPlus] Error initializing vote receiver. Please verify that the configured
[20:27:52 ERROR]: [VotifierPlus] IP address and port are not already in use. This is a common problem
[20:27:52 ERROR]: [VotifierPlus] with hosting services and, if so, you should check with your hosting provider.
[20:27:52 WARN]: java.net.BindException: Address already in use: bind

Need to use a different port. This is why I never recommend using votifier on a local server setup. Nearly impossible to setup.

**Comment by FlameBeast25** [comment]
wdym how to set up now

**Comment by FlameBeast25** [comment]
> [20:27:52 ERROR]: [VotifierPlus] Error initializing vote receiver. Please verify that the configured [20:27:52 ERROR]: [VotifierPlus] IP address and port are not already in use. This is a common problem [20:27:52 ERROR]: [VotifierPlus] with hosting services and, if so, you should check with your hosting provider. [20:27:52 WARN]: java.net.BindException: Address already in use: bind
> 
> Need to use a different port. This is why I never recommend using votifier on a local server setup. Nearly impossible to setup.

wait was i supposed to restart the server cause i just reloaded votfier OH WAIT i didn't reload votingplugin

**Comment by FlameBeast25** [comment]
> > [20:27:52 ERROR]: [VotifierPlus] Error initializing vote receiver. Please verify that the configured [20:27:52 ERROR]: [VotifierPlus] IP address and port are not already in use. This is a common problem [20:27:52 ERROR]: [VotifierPlus] with hosting services and, if so, you should check with your hosting provider. [20:27:52 WARN]: java.net.BindException: Address already in use: bind
> > Need to use a different port. This is why I never recommend using votifier on a local server setup. Nearly impossible to setup.
> 
> wait was i supposed to restart the server cause i just reloaded votfier OH WAIT i didn't reload votingplugin

![image](https://user-images.githubusercontent.com/89554319/189782549-5500e1ca-1162-4481-b796-b90235d85fff.png)

**Comment by BenCodez** [comment]
I would restart. You need to verify you have an open port selected. You're kinda on your own for this part. I can't find a port for you.

You might need to mess with permissions or something so it can bind, but you are all on your own.

I don't not recommend or really support local setups

**Comment by FlameBeast25** [comment]
> I would restart. You need to verify you have an open port selected. You're kinda on your own for this part. I can't find a port for you.
> 
> You might need to mess with permissions or something so it can bind, but you are all on your own.
> 
> I do not recommend or really support local setups

1 tutorial said to use any port that isn't the default one

**Comment by FlameBeast25** [comment]
Also can you add me on discord: FlameBeast 25 YT#1691

**Comment by BenCodez** [comment]
Just some open port

**Comment by FlameBeast25** [comment]
> Just some open port

just had to restart, it worked
how do i set up websites now

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Adding-VoteSites

**Comment by FlameBeast25** [comment]
> https://github.com/BenCodez/VotingPlugin/wiki/Adding-VoteSites

![image](https://user-images.githubusercontent.com/89554319/189788496-c9d08a24-6540-41f4-8a50-136fc3ab9dcd.png)
which one goes where

**Comment by BenCodez** [comment]
What?

**Comment by FlameBeast25** [comment]
> What?

which port goes where

**Comment by BenCodez** [comment]
The port you use?

**Comment by FlameBeast25** [comment]
> > What?
> 
> which port goes where

OH NVM I'm stupid
