### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.vexsoftware.votifier.net.VoteReceiver.shutdown()" because "this.voteReceiver" is null

### ISSUE THREAD

**Issue by O-legshiza** [BenCodez/VotifierPlus#39]
[18:20:41 WARN]: [VotifierPlus] Plugin VotifierPlus v1.0.7 generated an exception while executing task 366185
java.lang.NullPointerException: Cannot invoke "com.vexsoftware.votifier.net.VoteReceiver.shutdown()" because "this.voteReceiver" is null
        at com.vexsoftware.votifier.VotifierPlus.reload(VotifierPlus.java:294) ~[VotifierPlus.jar:?]
        at com.vexsoftware.votifier.commands.CommandLoader$2.execute(CommandLoader.java:69) ~[VotifierPlus.jar:?]
        at com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446) ~[VotifierPlus.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-55]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.3.jar:git-Pufferfish-55]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BenCodez** [comment]
Startup log?

**Comment by O-legshiza** [comment]
Sorry, this problem has gone with restart with newest version of plugin.
