### ISSUE TITLE
Help, I need this fixed!

### ISSUE THREAD

**Issue by NelmonXD** [BenCodez/VotifierPlus#42]
[21:28:23 WARN]: java.net.SocketTimeoutException: Connect timed out
[21:28:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[21:28:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[21:28:23 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:28:23 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[21:28:23 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.commands.CommandLoader$3.execute(CommandLoader.java:89)
[21:28:23 WARN]:        at VotifierPlus.jar//com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446)
[21:28:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:28:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:28:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:28:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:28:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:28:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

This is the error from console please help!

**Comment by BenCodez** [comment]
Check your settings, ask your host for which port

https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by NelmonXD** [comment]
So how do I get the good port?

**Comment by BenCodez** [comment]
Just find one that works

**Comment by NelmonXD** [comment]
How would i do that? haha!?

**Comment by NelmonXD** [comment]
![image](https://github.com/BenCodez/VotifierPlus/assets/124273000/d3680ad9-d4a3-4c87-8a73-5543bc10e7cc)

which one should i use

**Comment by BenCodez** [comment]
I got no idea

**Comment by NelmonXD** [comment]
Alright, I'll just try all of them

thanks for the help!

**Comment by NelmonXD** [comment]
[21:45:09 WARN]: java.lang.NullPointerException: Cannot invoke "com.vexsoftware.votifier.net.VoteReceiver.encrypt(byte[], java.security.PublicKey)" because the return value of "com.vexsoftware.votifier.VotifierPlus.getVoteReceiver()" is null
[21:45:09 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.commands.CommandLoader$3.execute(CommandLoader.java:91)
[21:45:09 WARN]:        at VotifierPlus.jar//com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446)
[21:45:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:45:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:45:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)


**Another error now?**

**Comment by NelmonXD** [comment]
Help?

**Comment by NelmonXD** [comment]
Hello? I need this plugin fixed as soon as possible.

**Comment by NelmonXD** [comment]
![image](https://github.com/BenCodez/VotifierPlus/assets/124273000/5d7a13b3-c69e-4bf1-9cc5-206688132951)

**Comment by NelmonXD** [comment]
@BenCodez

**Comment by BenCodez** [comment]
startup log?

**Comment by NelmonXD** [comment]
I don't know I tried adding it to a server list it still didnt work so i did /votifierplus test nelmon (which is my user) ee and it said check soneole for test results and it was that i think

**Comment by BenCodez** [comment]
send your startup, try testing with real votesites or test votifier websites

**Comment by NelmonXD** [comment]
i did it said 
![image](https://github.com/BenCodez/VotifierPlus/assets/124273000/f6b57e3c-3f63-4f37-9900-4b05836c6647)

**Comment by NelmonXD** [comment]
![image](https://github.com/BenCodez/VotifierPlus/assets/124273000/4a2f9e70-a181-4a5e-8344-cff83c2738cb)

**Comment by BenCodez** [comment]
well, I don't know, contact your host

**Comment by NelmonXD** [comment]
The server Ip is Nelmon.RageLands.net:25578 Would I use the 25578 as the port?

**Comment by BenCodez** [comment]
No, it needs to be different
