### ISSUE TITLE
Unable to establish a connection

### ISSUE THREAD

**Issue by ErrorHunter1** [BenCodez/VotifierPlus#43]
I tried to adjust everything, but the error comes that it doesn't work

Log: [23:46:12 WARN]: java.lang.NullPointerException: Cannot invoke "com.vexsoftware.votifier.net.VoteReceiver.encrypt(byte[], java.security.PublicKey)" because the return value of "com.vexsoftware.votifier.VotifierPlus.getVoteReceiver()" is null
[23:46:12 WARN]:        at VotifierPlus.jar//com.vexsoftware.votifier.commands.CommandLoader$3.execute(CommandLoader.java:91)
[23:46:12 WARN]:        at VotifierPlus.jar//com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446)
[23:46:12 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:46:12 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:46:12 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:46:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:46:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:46:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by BenCodez** [comment]
check startup log?

**Comment by ErrorHunter1** [comment]
> check startup log?

From the bungee cord or from the other server?

**Comment by BenCodez** [comment]
Whatever server that is

**Comment by ErrorHunter1** [comment]
My server 😅

I have set everything on the west side, set up the port for bungee and forwarding with the public key

**Comment by BenCodez** [comment]
Send your console log and config

**Comment by ErrorHunter1** [comment]
[latest.log](https://github.com/BenCodez/VotifierPlus/files/12340286/latest.log)

[config (1).log](https://github.com/BenCodez/VotifierPlus/files/12340300/config.1.log)

**Comment by BenCodez** [comment]
[23:43:33] [Server thread/ERROR]: [VotifierPlus] Error initializing vote receiver. Please verify that the configured
    [23:43:33] [Server thread/ERROR]: [VotifierPlus] IP address and port are not already in use. This is a common problem
    [23:43:33] [Server thread/ERROR]: [VotifierPlus] with hosting services and, if so, you should check with your hosting provider.
    [23:43:33] [Server thread/WARN]: java.net.BindException: Cannot assign requested address

**Comment by ErrorHunter1** [comment]
It worked I already had port but what forgot to activate thank you 🙏
