### ISSUE TITLE
Exception using Forwarding

### ISSUE THREAD

**Issue by DevJoey** [BenCodez/VotifierPlus#49]
I have setup vote-forwarding for use with a proxy-server and all is working fine. But if a vote gets received, a exception is thrown in the sub-server.

`[VotifierPlus] Exception caught while receiving a vote notification
[03.03 14:37:25.913] INFORMATION: [Testserver-1] [14:37:25 WARN]: java.lang.IllegalArgumentException: Last unit does not have enough valid bits
[03.03 14:37:25.914] INFORMATION: [Testserver-1] [14:37:25 WARN]:       at java.base/java.util.Base64$Decoder.decode0(Base64.java:868)
[03.03 14:37:25.914] INFORMATION: [Testserver-1] [14:37:25 WARN]:       at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
[03.03 14:37:25.915] INFORMATION: [Testserver-1] [14:37:25 WARN]:       at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
[03.03 14:37:25.916] INFORMATION: [Testserver-1] [14:37:25 WARN]:       at VotifierPlus.jar//com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:185)`

**Comment by BenCodez** [comment]
Answered you on spigot
