### ISSUE TITLE
tab complete votifierplus critical error

### ISSUE THREAD

**Issue by adamromulus** [BenCodez/VotifierPlus#5]
I got this when attempting to try out some commands before setup. 

```
[03:33:44] [Server thread/ERROR]: Exception when adamitude attempted to tab complete votifierplus 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/votifierplus ' in plugin VotifierPlus v1.0.1
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper.jar:git-Paper-161]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper.jar:git-Paper-161]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabCompleteCommand(CraftServer.java:1757) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1729) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:566) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[paper.jar:git-Paper-161]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:849) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1068) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:576) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:505) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[paper.jar:git-Paper-161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[paper.jar:git-Paper-161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.CommandHandler.hasPerm(CommandHandler.java:290) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.CommandHandler.getTabCompleteOptions(CommandHandler.java:237) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.TabCompleteHandler.getTabCompleteOptions(TabCompleteHandler.java:74) ~[?:?]
	at com.vexsoftware.votifier.commands.VotifierPlusTabCompleter.onTabComplete(VotifierPlusTabCompleter.java:36) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[paper.jar:git-Paper-161]
	... 19 more
```

and again

```
[03:33:50] [Server thread/ERROR]: Exception when adamitude attempted to tab complete votifierplus 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/votifierplus ' in plugin VotifierPlus v1.0.1
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper.jar:git-Paper-161]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper.jar:git-Paper-161]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabCompleteCommand(CraftServer.java:1757) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1729) ~[paper.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[paper.jar:git-Paper-161]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:566) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[paper.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[paper.jar:git-Paper-161]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:849) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1068) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:576) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:505) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[paper.jar:git-Paper-161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[paper.jar:git-Paper-161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.CommandHandler.hasPerm(CommandHandler.java:290) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.CommandHandler.getTabCompleteOptions(CommandHandler.java:237) ~[?:?]
	at com.ben12345rocks.VotifierPlus.AdvancedCore.CommandAPI.TabCompleteHandler.getTabCompleteOptions(TabCompleteHandler.java:74) ~[?:?]
	at com.vexsoftware.votifier.commands.VotifierPlusTabCompleter.onTabComplete(VotifierPlusTabCompleter.java:36) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[paper.jar:git-Paper-161]
	... 19 more
```

any ideas as to what's causing this? Thanks!

**Comment by Ben12345rocks** [comment]
I don't know, redownload the jar? More details?

**Comment by adamromulus** [comment]
I had just downloaded the jar, I'm running on Paper 1.15.2.

I'll try again with a new jar and post the results afterwards.
Thanks!
