### ISSUE TITLE
Problem with the RSA Key

### ISSUE THREAD

**Issue by raven4711** [BenCodez/VotifierPlus#53]
Fresh installed VotifierPlus 1.2.1 on Paper 1.20.4
JDK 17

[12:15:18] [Votifier I/O/INFO]: [VotifierPlus] Debug: Received vote record -> Vote (from:minecraft-server.eu username:G_S_Raven XXXXXX)
[12:15:18] [Votifier I/O/INFO]: [VotifierPlus] Debug: Sending vote to server1
[12:15:18] [Votifier I/O/WARN]: [VotifierPlus] Exception caught while receiving a vote notification
[12:15:18] [Votifier I/O/WARN]: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException: DerInputStream.getLength(): lengthTag=39, too big.
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:241)
[12:15:18] [Votifier I/O/WARN]:         at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:351)
[12:15:18] [Votifier I/O/WARN]:         at VotifierPlus_1.2.1.jar//com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:188)
[12:15:18] [Votifier I/O/WARN]: Caused by: java.security.InvalidKeyException: IOException: DerInputStream.getLength(): lengthTag=39, too big.
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.x509.X509Key.decode(X509Key.java:397)
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.x509.X509Key.decode(X509Key.java:402)
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.rsa.RSAPublicKeyImpl.<init>(RSAPublicKeyImpl.java:153)
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.rsa.RSAPublicKeyImpl.newKey(RSAPublicKeyImpl.java:80)
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.rsa.RSAKeyFactory.generatePublic(RSAKeyFactory.java:327)
[12:15:18] [Votifier I/O/WARN]:         at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:237)
[12:15:18] [Votifier I/O/WARN]:         ... 2 more

**Comment by BenCodez** [comment]
try deleting your key folder? And your using the correct key?

**Comment by raven4711** [comment]
Yes, that is the original Key from the installation - nothing modified.
And i copy the public Key to minecraft-server.eu

We used before nuVotifier and works perfectly... i would now try your Version

**Comment by BenCodez** [comment]
You can copy the keys from nuvotifier over and that should work.
