### ISSUE TITLE
Failed ( socket error )

### ISSUE THREAD

**Issue by PutraAxel** [BenCodez/VotifierPlus#64]
Not sure if this is a me issue but maybe someone can assist me.

I setup VoteifierPlus on Paper 1.21 server

Config:
Debug: EXTRA
host: 0.0.0.0
port: 25575
Forwarding:
server1:
Enabled: false
Host: ''
Port: ''

When i use a vote tester like https://mctools.org/votifier-tester i get this error :
[09:51:25 WARN] [VotifierPlus] Protocol error. Ignoring packet - Socket closed
[09:51:25 WARN] [VotifierPlus] java.net.SocketException: Socket closed
[09:51:25 WARN]  at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:682)
[09:51:25 WARN]  at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:755)
[09:51:25 WARN]  at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:695)
[09:51:25 WARN]  at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:660)
[09:51:25 WARN]  at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:636)
[09:51:25 WARN]  at java.base/java.net.ServerSocket.accept(ServerSocket.java:591)
[09:51:25 WARN]  at VotifierPlus.jar//com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:131)

**Comment by BenCodez** [comment]
Check your startup log?

**Comment by PutraAxel** [comment]
Where i can check?

**Comment by BenCodez** [comment]
your server log file
