### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by EncryptedCode1337** [BenCodez/VotifierPlus#65]
I downloaded the plugin into my proxy, configured it and still receive this error
[15:56:05 INFO] [VotifierPlus]: Debug: Sending vote to Wild-Box
[15:56:05 INFO] [VotifierPlus]: Failed to send vote to Wild-Box(________): Vote (from:Minecraft Menu username:_EncryptedCode address:___________timeStamp:1728575765), ignore this if server is offline. Enable debug to see the stacktrace
[15:56:05 ERROR]: java.net.ConnectException: Connection refused
[15:56:05 ERROR]:       at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[15:56:05 ERROR]:       at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
[15:56:05 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
[15:56:05 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[15:56:05 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[15:56:05 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:751)
[15:56:05 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:198)

**Comment by BenCodez** [comment]
Something about what server your forwarding to isn't correct

**Comment by EncryptedCode1337** [comment]
in the bungeeconfig.yml, in the "key" thing, i need to paste the public key to the server i want the vote to be forwarded?

**Comment by BenCodez** [comment]
If your talking about votingplugin then you don't need to forward, but otherwise yes

**Comment by EncryptedCode1337** [comment]
im not talking abt voting plugin, but is there a docs i can read?

**Comment by BenCodez** [comment]
For votingplugin yes, https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING. But for votifierplus no
