### ISSUE TITLE
Exception caught while receiving a vote notification

### ISSUE THREAD

**Issue by Gracesblades** [BenCodez/VotifierPlus#66]
keep getting an error when testing my voting, included log if that helps any, doesnt give much information

`[18:42:37] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)...
[18:42:37] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading localizations...
[18:42:37] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Connections will use NIO channels, Java compression, Java ciphers
[18:42:37] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading plugins...
[18:42:37] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Unable to load plugin plugins\PlaceholderAPI-2.11.6.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file PlaceholderAPI-2.11.6.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:283) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
[18:42:37] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Unable to load plugin plugins\ProtocolLib.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file ProtocolLib.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:283) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
[18:42:37] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Unable to load plugin plugins\Vault.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file Vault.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:283) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
[18:42:37] [main/INFO] [floodgate]: Took 119ms to boot Floodgate
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin floodgate 2.2.3-SNAPSHOT (b112-0360721) by GeyserMC
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin geyser 2.4.3-b689 (git-master-d64c0b3) by GeyserMC
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin mysqldriver 1.0 by BenCodez
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin venturechat 3.7.1 by Aust1n46
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin votifierplus 1.0 by BenCodez
[18:42:37] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin votingplugin 1.0 by BenCodez
[18:42:37] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 7 plugins
[18:42:37] [floodgate - Task Executor #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:42:37] [floodgate - Task Executor #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:42:38] [floodgate - Task Executor #0/INFO] [geyser]: Loading extensions...
[18:42:38] [floodgate - Task Executor #0/INFO] [geyser]: Loaded 0 extension(s)
[18:42:38] [floodgate - Task Executor #0/INFO] [votifierplus]: Votifier enabled.
[18:42:38] [floodgate - Task Executor #0/INFO] [votifierplus]: VotingPlugin velocity loaded, Internal Jar Version: 1.3
[18:42:38] [floodgate - Task Executor #0/INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[18:42:38] [floodgate - Task Executor #0/INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[18:42:38] [floodgate - Task Executor #0/INFO] [votingplugin]: VotingPlugin velocity loaded, method: PLUGINMESSAGING, PluginMessagingVersion: 1, Internal Jar Version: 6.17.1
[18:42:38] [Netty NIO Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0]:25565
[18:42:38] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: ******************************************
[18:42:38] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: 
[18:42:38] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: Loading Geyser version 2.4.3-b689 (git-master-d64c0b3)
[18:42:38] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: 
[18:42:38] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: ******************************************
[18:42:38] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (1.72s)!
[18:42:40] [nioEventLoopGroup-3-1/INFO] [geyser]: Started Geyser on UDP port 25565
[18:42:40] [Geyser-Velocity - Task Executor #0/INFO] [geyser]: Done (1.491s)! Run /geyser help for help!
[18:43:15] [Netty NIO Worker #0/INFO] [com.velocitypowered.proxy.connection.client.AuthSessionHandler]: [connected player] SouL_X_Crusader (/97.128.93.58:62701) has connected
[18:43:15] [Netty NIO Worker #0/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] SouL_X_Crusader -> Skyblock has connected
[18:43:31] [Votifier I/O/WARN] [votifierplus]: Exception caught while receiving a vote notification
`

**Comment by BenCodez** [comment]
Enable debug in votifier and send the log

**Comment by Gracesblades** [comment]
`[18:51:16 ERROR]: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Missing key encoding
[18:51:16 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:241)
[18:51:16 ERROR]:       at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:351)
[18:51:16 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:188)
[18:51:16 ERROR]: Caused by: java.security.InvalidKeyException: Missing key encoding
[18:51:16 ERROR]:       at java.base/sun.security.rsa.RSAPublicKeyImpl.<init>(RSAPublicKeyImpl.java:146)
[18:51:16 ERROR]:       at java.base/sun.security.rsa.RSAPublicKeyImpl.newKey(RSAPublicKeyImpl.java:80)
[18:51:16 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.generatePublic(RSAKeyFactory.java:324)
[18:51:16 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:237)
[18:51:16 ERROR]:       ... 2 more`

**Comment by BenCodez** [comment]
regenerate your keys

**Comment by Gracesblades** [comment]
getting the same error

**Comment by BenCodez** [comment]
https://www.devglan.com/online-tools/rsa-encryption-decryption set it to 2048 bits and generate keys and set them as your new keys

**Comment by Gracesblades** [comment]
did so and now its atleast saying that its sending to my skyblock server but then gets same error



`[18:59:42 INFO] [votifierplus]: Debug: Sending vote to Skyblock
[18:59:42 WARN] [votifierplus]: Exception caught while receiving a vote notification
[18:59:42 ERROR]: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Missing key encoding
[18:59:42 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:241)
[18:59:42 ERROR]:       at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:351)
[18:59:42 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:188)
[18:59:42 ERROR]: Caused by: java.security.InvalidKeyException: Missing key encoding
[18:59:42 ERROR]:       at java.base/sun.security.rsa.RSAPublicKeyImpl.<init>(RSAPublicKeyImpl.java:146)
[18:59:42 ERROR]:       at java.base/sun.security.rsa.RSAPublicKeyImpl.newKey(RSAPublicKeyImpl.java:80)
[18:59:42 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.generatePublic(RSAKeyFactory.java:324)
[18:59:42 ERROR]:       at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:237)
[18:59:42 ERROR]:       ... 2 more`

**Comment by BenCodez** [comment]
you'll have to do that on all servers, just make new keys, or use votingplugin forwarding if your using that

**Comment by Gracesblades** [comment]
im using votingplugin, as far as im aware theres no where to put the private keys on the backend servers

**Comment by BenCodez** [comment]
then you should be doing this https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING instead of forwarding with votifierplus

**Comment by Gracesblades** [comment]
i am doing so, is there a certain setting to change within votifierplus? i am using pluginmessaging on velocity and backend, votifier only on proxy, setup mysql data which it isnt giving any errors for and created tables in

**Comment by Gracesblades** [comment]
if im correct redis and global were to be left disabled in votingplugin

**Comment by BenCodez** [comment]
Wanna try using nuvotifier and see if the same issue happens?

**Comment by Gracesblades** [comment]
does votifier work up to 1.20.4? wasnt sure if it did or not. always used votifier lol first time using a proxy server, one issue i found through the troubleshooting guide, using cmd /votingpluginbungee status  is unfound on my server

**Comment by BenCodez** [comment]
yes it works, just not sure what's going on in your case right now

**Comment by Gracesblades** [comment]
okay will give it a shot! much thanks and appreciation for the quick and fast responses!
