### ISSUE TITLE
Velocity and voting

### ISSUE THREAD

**Issue by GothkittyGirl** [BenCodez/VotifierPlus#76]
Hi ive have a really hard time sending votes to my server. i got everything setup the vote posted to my velocity server but gives me this error:

[votifierplus]: Exception caught while receiving a vote notification

and idk what ive done wrong

**Comment by BenCodez** [comment]
Send startup log

**Comment by GothkittyGirl** [comment]
[latest.log](https://github.com/user-attachments/files/17982211/latest.log)

**Comment by BenCodez** [comment]
If your using VotingPlugin you only need it on one server


    [17:00:52] [Velocity - Task Executor #0/ERROR] [votifierplus]: Error initializing vote receiver. Please verify that the configured
    [17:00:52] [Velocity - Task Executor #0/ERROR] [votifierplus]: IP address and port are not already in use. This is a common problem
    [17:00:52] [Velocity - Task Executor #0/ERROR] [votifierplus]: with hosting services and, if so, you should check with your hosting provider.
    [17:00:52] [Velocity - Task Executor #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.net.BindException: Address already in use

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING just velocity if using votingplugin

**Comment by GothkittyGirl** [comment]
ok so ive removed them from all others  and still getting this error

votifierplus reload
[21:49:27 ERROR] [votifierplus]: Error initializing vote receiver. Please verify that the configured
[21:49:27 ERROR] [votifierplus]: IP address and port are not already in use. This is a common problem
[21:49:27 ERROR] [votifierplus]: with hosting services and, if so, you should check with your hosting provider.
[21:49:27 ERROR]: java.net.BindException: Address already in use
[21:49:27 ERROR]:       at java.base/sun.nio.ch.Net.bind0(Native Method)
[21:49:27 ERROR]:       at java.base/sun.nio.ch.Net.bind(Net.java:565)
[21:49:27 ERROR]:       at java.base/sun.nio.ch.Net.bind(Net.java:554)
[21:49:27 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:636)
[21:49:27 ERROR]:       at java.base/java.net.ServerSocket.bind(ServerSocket.java:391)
[21:49:27 ERROR]:       at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.initialize(VoteReceiver.java:87)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.net.VoteReceiver.<init>(VoteReceiver.java:81)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.velocity.VotifierPlusVelocity$1.<init>(VotifierPlusVelocity.java:194)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.velocity.VotifierPlusVelocity.loadVoteReceiver(VotifierPlusVelocity.java:194)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.velocity.VotifierPlusVelocity.reload(VotifierPlusVelocity.java:266)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.velocity.VotifierPlusVelocityCommand.execute(VotifierPlusVelocityCommand.java:34)
[21:49:27 ERROR]:       at com.vexsoftware.votifier.velocity.VotifierPlusVelocityCommand.execute(VotifierPlusVelocityCommand.java:18)
[21:49:27 ERROR]:       at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:82)
[21:49:27 ERROR]:       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[21:49:27 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:236)
[21:49:27 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:277)
[21:49:27 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[21:49:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:49:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:49:27 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[21:49:27 INFO]: Reloading VotifierPlus

**Comment by BenCodez** [comment]
You need a host/port not in use

**Comment by GothkittyGirl** [comment]
Debug: true
host: 0.0.0.0
port: 8166
Forwarding:
  Survival:
    Enabled: true
    Host: '149.56.155.38'
    Port: '8012'
    Key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw4mQfnKwJXnD9RmI6AokHlGN7D0TmeV3TWiCkNP49/uTiM51O7EBI/pgtp+jmJiSCvMDBkoDwmRsiHzVDi7B108XkibiciVQ1DwG6+1+akVcArOB+IorNefxPObZ0gHGgf/CaxdlzKI4Xm+BgZ3HOMpIg4cJ82HfmegCzg5WXIYdcHoTFl8APlBijb/2KuZ0qvp+WR6M0r6hakXYfWxEvB/+p3F4QrIOUMAR6gbo1/Z2kqqcn1AUFcdxzprhMH5XV1vftWzUwaxCWjELWFCUmPsuLdThgqpav/UFZTv2Mbl/jWPZeqBaREAInl3Hs4CsW3oyhuccaJQ3OxL2GuEm9QIDAQAB'
  Skyblock:
    Enabled: true
    Host: '66.70.237.129'
    Port: '8005'
    Key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArRTSnSRUJsj0mC4wT9fp9yeK1QG3B/xhBlblNmuDEfhB4DZqlfkX8Jr+Tn5CJQ0ytTO800t932CqbOtdEzuZQaklxZ4ZtLM7Cq+pADxSyHNl3FBStz49SdYonuDSH0f2Sv2ukofINNpv2AUl8CPjtgCdfwvcWpgFmStgUmrEtHZVs6KaMrdbtJ6tbtXkn7o5lVpO7fRndtoQWlUCdzNBCYs+JLdY9WRGk3bTs3QZ3dP/uJzF9Vl+ybeNMGMFKjNwnnzE2nGgmPFI13gtgfE7j7/ftdGD5snAhYItNFDJzy/Yji+A+vaB70fLDRLHQZnbMwOQkXPNtmI8PNKrkW32dQIDAQAB'

**Comment by BenCodez** [comment]
disable votifier forwarding if your not using. Try a server restart

**Comment by GothkittyGirl** [comment]
dont i need that for servers to get the votes?

**Comment by GothkittyGirl** [comment]
so Enabled: false?

**Comment by BenCodez** [comment]
You never answered my question if your using votingplugin to handle that or not, so I have no idea what your trying to do

**Comment by GothkittyGirl** [comment]
yes i am sorry

**Comment by GothkittyGirl** [comment]
> https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING just velocity if using votingplugin

Idk what parts of this im supposed to do :/

**Comment by BenCodez** [comment]
> > https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING just velocity if using votingplugin
> 
> Idk what parts of this im supposed to do :/ the plugin it say to install doesnt work on my velocity server

Did you read the wiki? It says what to do

**Comment by GothkittyGirl** [comment]
> > > https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING just velocity if using votingplugin
> > 
> > 
> > Idk what parts of this im supposed to do :/ the plugin it say to install doesnt work on my velocity server
> 
> Did you read the wiki? It says what to do

it really hard to understand :/

**Comment by BenCodez** [comment]
What have you done? What have you tried? I can't help if you don't provide any information.

**Comment by GothkittyGirl** [comment]
Running on velocity:
Velocity requires a mysql driver to be installed, one available [here](http://bencodez.com/job/MySQLDriver/) (install as a plugin in plugin folder) will allow VotingPlugin to run on velocity with no compatibility layer. Works the exact same as bungeecord.

this part is all i needed to do right?

**Comment by BenCodez** [comment]
That plus all other settings

**Comment by GothkittyGirl** [comment]
plus im using votifier plus.. it say nuvotifier which i dont have

**Comment by GothkittyGirl** [comment]
ok so i just got back and looking i dont see this part in my stuff

Bungee/Proxy (VotingPlugin settings, bungeeconfig.yml):

    Votifier setup on here only (no forwarding, nuvotifier forwarding method set to none)
    BungeeMethod: PLUGINMESSAGING
    SendVotesToAllServers: true (for a reward on each server) or false (reward on whatever server player connects to first)
    Set MySQL settings, must match same table as the other servers (MySQL is required)

**Comment by BenCodez** [comment]
look in bungeeconfig.yml of votingplugin
